# -*- coding: utf-8 -*-
"""ETL_Eduardo_Reis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tOBHqwFBi2gmndMiNozzcEdgN30AAoQ-
"""

import pandas as pd
import json
import os
from google.colab import files

# ==========================================
# 1. ETAPA DE EXTRAÇÃO (EXTRACT)
# ==========================================
print("--- Iniciando Extração ---")

# Criando um arquivo de exemplo caso ele não exista no Colab
if not os.path.exists('SDW2023.csv'):
    print("Criando arquivo SDW2023.csv de exemplo...")
    data = {
        'UserID': [1, 2, 3, 4, 5],
        'Nome': ['Naruto Uzumaki', 'Hinata Hyuga', 'Sasuke Uchiha', 'Sakura Haruno', 'Kakashi Hatake']
    }
    pd.DataFrame(data).to_csv('SDW2023.csv', index=False)

# Lendo os dados
df_users = pd.read_csv('SDW2023.csv')
users = df_users.to_dict(orient='records')
print(f"Extraídos {len(users)} usuários.")

# ==========================================
# 2. ETAPA DE TRANSFORMAÇÃO (TRANSFORM)
# ==========================================
print("\n--- Iniciando Transformação ---")

def generate_ai_message(user_name):
    """
    Simula a personalização via IA.
    """
    return f"Olá {user_name}! O Santander acredita no seu potencial. Que tal diversificar seus investimentos hoje para garantir um futuro extraordinário?"

for user in users:
    # Gerando a mensagem personalizada
    message = generate_ai_message(user['Nome'])

    # Criando a estrutura de 'news'
    user['news'] = [
        {
            "icon": "https://digitalinnovationone.github.io/santander-dev-week-2023-api/icons/money.svg",
            "description": message
        }
    ]
print("Mensagens personalizadas geradas com sucesso.")

# ==========================================
# 3. ETAPA DE CARREGAMENTO (LOAD) - CORRIGIDA
# ==========================================
print("\n--- Iniciando Carregamento ---")

# 1. Salvando em JSON (Aqui usamos ensure_ascii=False para manter os acentos)
output_json = 'SDW2023_output.json'
with open(output_json, 'w', encoding='utf-8') as f:
    json.dump(users, f, ensure_ascii=False, indent=4)

# 2. Salvando em CSV (O segredo está no 'utf-8-sig')
output_csv = 'SDW2023_final.csv'
df_final = pd.DataFrame(users)
df_final['MarketingMessage'] = df_final['news'].apply(lambda x: x[0]['description'])

# A CORREÇÃO ESTÁ AQUI: encoding='utf-8-sig'
df_final.drop(columns=['news']).to_csv(output_csv, index=False, encoding='utf-8-sig')

print(f"Arquivos gerados com codificação corrigida!")
files.download(output_csv)



